name: Release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - staging
          - production
          - whitelabel1
          - whitelabel2
          - whitelabel3

jobs:
  trigger:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ inputs.environment }}
      ref: ${{ github.ref }}
